"""initial_schema

Revision ID: 3e3f1266ac84
Revises:
Create Date: 2025-12-29 18:43:11.748254+00:00

"""

from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3e3f1266ac84"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_keys",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("owner_email", sa.String(length=255), nullable=True),
        sa.Column("rate_limit_per_minute", sa.Integer(), nullable=False),
        sa.Column("rate_limit_per_day", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("total_requests", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_keys")),
    )
    op.create_index(op.f("ix_api_keys_key"), "api_keys", ["key"], unique=True)
    op.create_table(
        "cached_locations",
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="POINT", srid=4326, from_text="ST_GeomFromEWKT", name="geometry"
            ),
            nullable=True,
        ),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("interpolation_model", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("data_tier", sa.String(length=20), nullable=False),
        sa.Column("source_dataset", sa.String(length=50), nullable=False),
        sa.Column("country_code", sa.String(length=3), nullable=True),
        sa.Column("cache_ttl_days", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cached_locations")),
    )
    # Note: GIST index on geom is created automatically by GeoAlchemy2
    op.create_index(
        "ix_cached_locations_data_tier", "cached_locations", ["data_tier"], unique=False
    )
    op.create_index(
        "ix_cached_locations_lat_lon", "cached_locations", ["latitude", "longitude"], unique=False
    )
    op.create_table(
        "solar_analyses",
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("area_m2", sa.Float(), nullable=False),
        sa.Column("tilt", sa.Float(), nullable=True),
        sa.Column("orientation", sa.String(length=5), nullable=True),
        sa.Column("annual_generation_kwh", sa.Float(), nullable=True),
        sa.Column("monthly_breakdown", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("peak_month", sa.String(length=20), nullable=True),
        sa.Column("worst_month", sa.String(length=20), nullable=True),
        sa.Column("data_tier", sa.String(length=20), nullable=False),
        sa.Column("confidence_score", sa.Float(), nullable=False),
        sa.Column("ai_insights", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("country_code", sa.String(length=3), nullable=True),
        sa.Column("applied_plugin", sa.String(length=50), nullable=True),
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("api_key_id", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_solar_analyses")),
    )
    op.create_index(
        op.f("ix_solar_analyses_request_id"), "solar_analyses", ["request_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_solar_analyses_request_id"), table_name="solar_analyses")
    op.drop_table("solar_analyses")
    op.drop_index("ix_cached_locations_lat_lon", table_name="cached_locations")
    op.drop_index("ix_cached_locations_data_tier", table_name="cached_locations")
    # Note: idx_cached_locations_geom is dropped automatically with table (GeoAlchemy2)
    op.drop_table("cached_locations")
    op.drop_index(op.f("ix_api_keys_key"), table_name="api_keys")
    op.drop_table("api_keys")
    # ### end Alembic commands ###
